const PREFIX = "https://neon.jiker.vip";
// const PREFIX = "http://127.0.0.1:7001";

export default {
  qiniuToken: `${PREFIX}/api/qiniu/token`,
  course: `${PREFIX}/api/course`,
  chapter: `${PREFIX}/api/chapter`,
  section: `${PREFIX}/api/section`,
  courseItem: id => `${PREFIX}/api/course/${id}`,
  chapterItem: id => `${PREFIX}/api/chapter/${id}`,
  sectionItem: id => `${PREFIX}/api/section/${id}`,
  chapterSort: `${PREFIX}/api/chapter/sort`,
  sectionSort: `${PREFIX}/api/section/sort`,
  zhiye: `${PREFIX}/api/zhiye`,
  zhiyeItem: id => `${PREFIX}/api/zhiye/${id}`,
  zhiyePath: `${PREFIX}/api/zhiye/path`,
  zhiyePathItem: id => `${PREFIX}/api/zhiye/path/${id}`,
  zhiyePathSort: `${PREFIX}/api/zhiye/path/sort`,
  zhiyeCourse: `${PREFIX}/api/zhiye/course`,
  zhiyeCourseItem: id => `${PREFIX}/api/zhiye/course/${id}`,
  zhiyeCourseSort: `${PREFIX}/api/zhiye/course/sort`,
  company: `${PREFIX}/api/company`,
  companyItem: id => `${PREFIX}/api/company/${id}`,
  project: `${PREFIX}/api/project`,
  projectItem: id => `${PREFIX}/api/project/${id}`,
  projectVersion: `${PREFIX}/api/version`,
  projectVersionItem: id => `${PREFIX}/api/version/${id}`,
  projectStory: `${PREFIX}/api/story`,
  projectStoryItem: id => `${PREFIX}/api/story/${id}`,
  projectTask: `${PREFIX}/api/task`,
  projectTaskItem: id => `${PREFIX}/api/task/${id}`,
  projectVersionSort: `${PREFIX}/api/project/version/sort`,
  projectStorySort: `${PREFIX}/api/project/story/sort`,
  projectTaskSort: `${PREFIX}/api/project/task/sort`
};
